#include <Miro/Miro.h>
#include <NanoTest/NanoTest.h>

#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

using namespace nano;

// Compile-time serde coverage: types whose reflect() (generated by
// MIRO_REFLECT) and constructors are constexpr can run toJSONString /
// fromJSONString / createFromJSONString inside constant expressions.
// The static_asserts here ARE the tests; the runtime tests check that
// the compile-time path and the runtime path produce identical bytes.

namespace
{

enum class Channel
{
    Left,
    Right,
    Side
};

struct Track
{
    int id = 0;
    std::string name;
    float gain = 0.0f;

    bool operator==(const Track&) const = default;

    MIRO_REFLECT(id, name, gain)
};

struct Session
{
    std::string title;
    int sampleRate = 0;
    double tempo = 0.0;
    bool looping = false;
    std::int16_t depth = 0;
    Channel channel = Channel::Left;
    std::optional<int> takeCount;
    std::vector<Track> tracks;
    std::vector<int> markers;
    std::array<double, 2> range {};
    Track master;

    bool operator==(const Session&) const = default;

    MIRO_REFLECT(title,
                 sampleRate,
                 tempo,
                 looping,
                 depth,
                 channel,
                 takeCount,
                 tracks,
                 markers,
                 range,
                 master)
};

constexpr Session makeSession()
{
    auto session = Session {};
    session.title = "Demo \"mix\"\n";
    session.sampleRate = 48000;
    session.tempo = 117.5;
    session.looping = true;
    session.depth = -24;
    session.channel = Channel::Side;
    session.takeCount = 3;
    session.tracks = {Track {1, "kick", 0.5f}, Track {2, "snare", -6.25f}};
    session.markers = {0, 96000};
    session.range = {0.25, 1e-9};
    session.master = Track {99, "mix bus", 1.0f};
    return session;
}

// Captured from the runtime path (Json::print over std::map-backed
// values); the static_asserts below prove the compile-time path emits
// the same bytes, key-sorted included.
constexpr auto sessionJson = std::string_view {
    R"({"channel":"Side","depth":-24,"looping":true,"markers":[0,96000],)"
    R"("master":{"gain":1,"id":99,"name":"mix bus"},"range":[0.25,1e-09],)"
    R"("sampleRate":48000,"takeCount":3,"tempo":117.5,)"
    R"("title":"Demo \"mix\"\n",)"
    R"("tracks":[{"gain":0.5,"id":1,"name":"kick"},)"
    R"({"gain":-6.25,"id":2,"name":"snare"}]})"};

constexpr auto trackJsonIndented =
    std::string_view {"{\n  \"gain\": 0.5,\n  \"id\": 1,\n  \"name\": \"kick\"\n}"};

// --- Compile-time serialization ---

static_assert(Miro::toJSONString(makeSession()) == sessionJson);
static_assert(Miro::toJSONString(Track {1, "kick", 0.5f}, 2) == trackJsonIndented);

// --- Compile-time parsing & round-trips ---

static_assert(Miro::createFromJSONString<Session>(sessionJson) == makeSession());
static_assert(Miro::createFromJSONString<Session>(Miro::toJSONString(makeSession()))
              == makeSession());
static_assert(Miro::toJSONString(Miro::createFromJSONString<Session>(sessionJson))
              == sessionJson);

// Parser features: comments, unknown keys, null for optionals,
// missing keys preserving existing values, escapes, exponents.
constexpr Session parsePartial()
{
    auto session = makeSession();

    Miro::fromJSONString(session, R"({
        // line comment
        "tempo": 2.5e2, /* block comment */
        "takeCount": null,
        "unknown": {"deep": [1, {"x": null}, "A"]},
        "title": "café € \t",
        "depth": 8
    })");

    return session;
}

static_assert(parsePartial().tempo == 250.0);
static_assert(!parsePartial().takeCount.has_value());
static_assert(parsePartial().title == "caf\xc3\xa9 \xe2\x82\xac \t");
static_assert(parsePartial().depth == 8);
static_assert(parsePartial().sampleRate == 48000); // missing key untouched
static_assert(parsePartial().channel == Channel::Side);

// Enums load from either their name or their numeric value.
static_assert(Miro::createFromJSONString<Track>(R"({"id": 2e1})").id == 20);
static_assert(Miro::createFromJSONString<Session>(R"({"channel": "Right"})").channel
              == Channel::Right);
static_assert(Miro::createFromJSONString<Session>(R"({"channel": 2})").channel
              == Channel::Side);

// A literal type (no allocating members) parsed at compile time can
// live in a constexpr variable.
struct Bounds
{
    int low = 0;
    int high = 0;
    bool inclusive = false;
    std::array<double, 3> weights {};
    Channel channel = Channel::Left;

    bool operator==(const Bounds&) const = default;

    MIRO_REFLECT(low, high, inclusive, weights, channel)
};

constexpr auto bounds = Miro::createFromJSONString<Bounds>(
    R"({"low": -3, "high": 12, "inclusive": true,
        "weights": [0.5, 1.5, 2.5], "channel": "Right"})");

static_assert(bounds.low == -3);
static_assert(bounds.high == 12);
static_assert(bounds.inclusive);
static_assert(bounds.weights[2] == 2.5);
static_assert(bounds.channel == Channel::Right);

// Hand-written constexpr reflect() bodies work too.
struct Gain
{
    double linear = 1.0;

    constexpr void reflect(Miro::Reflector& ref) { MIRO_FIELDS(ref, linear); }
};

static_assert(Miro::createFromJSONString<Gain>(R"({"linear": 0.25})").linear
              == 0.25);

// --- Runtime parity ---

auto constexprMatchesRuntimeCompact =
    test("Constexpr serde: compile-time JSON matches runtime JSON") = []
{ check(Miro::toJSONString(makeSession()) == std::string {sessionJson}); };

auto constexprMatchesRuntimeIndented =
    test("Constexpr serde: compile-time indented JSON matches runtime") = []
{
    check(Miro::toJSONString(Track {1, "kick", 0.5f}, 2)
          == std::string {trackJsonIndented});
};

auto runtimeRoundTripOfSample =
    test("Constexpr serde: runtime round-trip of the same sample") = []
{
    check(Miro::createFromJSONString<Session>(Miro::toJSONString(makeSession()))
          == makeSession());
};

// The constexpr printer/parser are also callable at runtime — sweep
// them against the runtime Json printer/parser for byte and bit
// parity across representative numbers.
auto numberFormattingParity =
    test("Constexpr serde: number formatting matches runtime printer") = []
{
    auto values = std::vector<double> {
        0.0,        -0.0,   1.0,     -1.0,  42.0,   -17.0,     1e14,
        -1e15,      1e15,   3.14,    -2.5,  0.5,    117.5,     1e-9,
        6.25e-5,    0.0001, 0.00001, 0.1,   0.2,    1.0 / 3.0, 1234567.5,
        9.999999e8, 2.5e-3, 1e100,   1e308, 5e-324, 123.456};

    for (auto value: values)
    {
        auto mirror = Miro::Detail::ConstexprJson::Value {};
        mirror.kind = Miro::Detail::ConstexprJson::Value::Kind::Number;
        mirror.numberValue = value;

        check(Miro::Detail::ConstexprJson::print(mirror, 0)
              == Miro::Json::print(Miro::JSON {value}, 0));
    }
};

auto numberParsingParity =
    test("Constexpr serde: number parsing matches runtime parser") = []
{
    // All within the exact single-multiply fast path (mantissa <= 19
    // digits, net power of ten within ±22), where the constexpr
    // parser is bit-identical to strtod.
    auto inputs = std::vector<std::string> {"0",
                                            "-0",
                                            "42",
                                            "-17.25",
                                            "3.14",
                                            "1e10",
                                            "2.5e-3",
                                            "117.5",
                                            "1e-9",
                                            "0.000125",
                                            "9007199254740993",
                                            "9999999999999999999",
                                            "1.25e+15",
                                            "0.1"};

    for (auto& text: inputs)
    {
        auto parsed = Miro::Detail::ConstexprJson::parse(text);
        check(parsed.numberValue == Miro::Json::parse(text).asNumber());
    }
};

} // namespace
