#!/usr/bin/env python3
"""Generates Lib/Miro/Unicode/GeneralCategoryTable.h from Python's unicodedata.

The table is a run-start array: walk 0..0x10FFFF and emit one entry every
time the general category changes.  Each entry packs the run's first code
point and its category into a single 32-bit word as

    (codePoint << 5) | category

which fits because a code point needs 21 bits and there are 30 categories.
Packing this way keeps the array sorted by code point, so a lookup is one
std::upper_bound minus one.

Usage:  python3 Tools/GenerateUnicodeTable.py
"""

import sys
import unicodedata
from pathlib import Path

# Order must match Miro::Unicode::GeneralCategory in Unicode/Unicode.h.
# The 30 values are grouped by major class so the class predicates are
# range tests on the enum value.
CATEGORIES = [
    "Lu", "Ll", "Lt", "Lm", "Lo",
    "Mn", "Mc", "Me",
    "Nd", "Nl", "No",
    "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
    "Sm", "Sc", "Sk", "So",
    "Zs", "Zl", "Zp",
    "Cc", "Cf", "Cs", "Co", "Cn",
]

MAX_CODE_POINT = 0x10FFFF
VALUES_PER_LINE = 6

SCRIPT_NAME = "Tools/GenerateUnicodeTable.py"
OUTPUT_PATH = "Lib/Miro/Unicode/GeneralCategoryTable.h"


def category_index(code_point):
    return CATEGORIES.index(unicodedata.category(chr(code_point)))


def build_runs():
    runs = []
    previous = None

    for code_point in range(MAX_CODE_POINT + 1):
        current = category_index(code_point)

        if current != previous:
            runs.append((code_point, current))
            previous = current

    return runs


def render(runs):
    python_version = ".".join(str(part) for part in sys.version_info[:3])

    lines = [
        "#pragma once",
        "",
        f"// Generated by {SCRIPT_NAME} — do not edit by hand.",
        "//",
        f"// Unicode {unicodedata.unidata_version}, via the unicodedata module of",
        f"// Python {python_version}.  Regenerate with:",
        "//",
        f"//     python3 {SCRIPT_NAME}",
        "//",
        "// Each entry starts a run of code points sharing one general",
        "// category, packed as (codePoint << 5) | category.  The runs are",
        "// sorted and contiguous, so the run beginning at entry i covers",
        "// every code point up to the one before entry i + 1, and the last",
        "// run reaches U+10FFFF.  The category index is an offset into",
        "// Miro::Unicode::GeneralCategory.",
        "",
        "#include <cstdint>",
        "",
        "namespace Miro::Unicode::Detail",
        "{",
        "",
        f"// {len(runs)} runs.",
        "// clang-format off",
        "inline constexpr std::uint32_t generalCategoryRuns[] = {",
    ]

    packed = [(start << 5) | category for start, category in runs]

    for index in range(0, len(packed), VALUES_PER_LINE):
        row = packed[index : index + VALUES_PER_LINE]
        lines.append("    " + " ".join(f"0x{value:08X}," for value in row))

    lines += [
        "};",
        "// clang-format on",
        "",
        "} // namespace Miro::Unicode::Detail",
        "",
    ]

    return "\n".join(lines)


def main():
    runs = build_runs()

    output = Path(__file__).resolve().parent.parent / OUTPUT_PATH
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(runs), encoding="utf-8")

    print(f"Unicode {unicodedata.unidata_version}: {len(runs)} runs -> {output}")


if __name__ == "__main__":
    main()
